### ISSUE TITLE
Typo in about?

### ISSUE THREAD

**Issue by elvey** [testifysec/witness#177]
Witness is a pluggable framework for software supply chain risk management.  It automates, normalizes, and verifies software artifact prov**ide**nce 
_should be_:
Witness is a pluggable framework for software supply chain risk management.  It automates, normalizes, and verifies software artifact prov**ena**nce
_because_
Provenance (from the French provenir, 'to come from/forth') is the chronology of the ownership, custody or location of a historical object.
(Note: this isn't in the code base; it's metadata; editable under the gear icon on the project main page, so a pull request isn't possible.)

**Comment by mikhailswift** [comment]
Thanks for pointing this out!
