### ISSUE TITLE
Give better error when bad flags are used

### ISSUE THREAD

**Issue by colek42** [testifysec/witness#203]
Currently, when an unknown flag is used witness does not give an error message and exits.  We should notify the user which flag in unknown and print the help.

**Comment by mikhailswift** [comment]
This is due to all the cobra commands having SilenceErrors set to true, however disabling this causes weird error output:

```
INFO    Starting oci attestor...
error getting canidate: no products to attest
Error: failed to run attestors: no products to attest
ERROR   failed to run attestors: no products to attest
exit status 1
```
