### ISSUE TITLE
Rekor Integration is Broken

### ISSUE THREAD

**Issue by jmeth** [testifysec/witness#212]
When running witness with a rekor server using the `-r` flag the attestation fails to upload because rekor does not recognize the `dsse` type. The attestation successfully uploads when manually using the rekor-cli tool. I believe this is because originally witness was integrating with a forked version of rekor with `dsse` type but the upstream rekor project integrated the payload as `intoto:0.0.2` type instead.

```sh
[root@dev witness]# witness version
INFO    Using config file: .witness.yaml
witness v0.1.11-d7c6718

[root@dev witness]# witness run -k witness.key -r http://localhost:3000 -o build-att.json -s docker-build -- docker build -t test:latest .
INFO    Using config file: .witness.yaml
INFO    Starting environment attestor...
INFO    Starting git attestor...
INFO    Starting material attestor...
INFO    Starting command-run attestor...
Sending build context to Docker daemon  6.436MB
Step 1/2 : FROM alpine:latest
 ---> 9c6f07244728
Step 2/2 : LABEL maintainer=solute.us
 ---> Using cache
 ---> 5d9469900750
Successfully built 5d9469900750
Successfully tagged test:latest
INFO    Starting product attestor...
ERROR   failed to store artifact in rekor: [POST /api/v1/log/entries][422] createLogEntry default  &{Code:422 Message:invalid kind value: "dsse"}

[root@dev witness]# rekor-cli upload --public-key witness.pub --artifact build-att.json --type intoto:0.0.2 --rekor_server http://localhost:3000
Created entry at index 19, available at: http://localhost:3000/api/v1/log/entries/0cb58854d00fe050c9dfc0a3f1e2da922d2e2c2d7e17ce415e22216be7ceb8fd887eb9b9c53184de

```

**Comment by jmeth** [comment]
It looks like the issue is actually in `go-witness` repo so I can move this issue over that if that is better.

https://github.com/testifysec/go-witness/blob/v0.1.12/rekor/rekor.go#L81

Also I noticed that the rekor code was removed in v0.1.13 so maybe this is something that is planned to be refactored in a newer version?

**Comment by mikhailswift** [comment]
Hi @jmeth .

Yes, the Rekor support is something we're taking another look at. The Rekor dsse type was in a pull request that has now been merged in with the type changed to in-toto v0.0.2.

**Comment by jmeth** [comment]
@mikhailswift ,
Is there a way we could introduce a temporary fix while you guys take another look at rekor support? I'd be willing to take a crack at it if you tell me how/where you would want to add that fix.
At the very least, I could submit a PR to the README here to clarify that rekor support with the `-r` flag is only for the `testifysec/rekor` build but that manual uploads to a rekor server work just fine.

**Comment by jmeth** [comment]
@mikhailswift I think I have a working patch against the v0.1.12 tag [here](https://github.com/jmeth/go-witness/commit/d925c4ff8632d53bd6910fa5a59e9f724be0a166)

A couple of notes:

* I don't know that I can create a PR against a tag, I think it has to be against a branch. So if this looks good and I submit I'm not sure which branch to use or if you would create one off of the v0.1.12 tag.
* I built and tested the witness cli and verified the `-r` flag with `witness run` and `witness verify` against a locally running rekor server and everything looked good
* I had to upgrade the rekor dependency so I ran `go mod tidy`
* Right now the unit tests fail. I think there are possibly 2 issues: 1) It seems the rekor integration only really works with the ed25519 key type. I tried a standard RSA key and that failed. I'm wondering if the test cases use a non supported key type? and 2) the test cases seem to still have "dsse" type in the responses. I'm not sure I'm able to regenerate test cases without a key.

```
--- FAIL: Test_wrappedRekorClient_StoreArtifact (0.00s)
    rekor_test.go:141: 
                Error Trace:    /home/josh/repos/github.com/jmeth/go-witness/rekor/rekor_test.go:141
                Error:          Received unexpected error:
                                could not verify envelope: Accepted signatures do not match threshold, Found: 0, Expected 1
                Test:           Test_wrappedRekorClient_StoreArtifact
--- FAIL: Test_FindEvidence (0.00s)
    rekor_test.go:181: 
                Error Trace:    /home/josh/repos/github.com/jmeth/go-witness/rekor/rekor_test.go:181
                Error:          Received unexpected error:
                                couldn't parse rekor entry: invalid kind value: "dsse"
                Test:           Test_FindEvidence
```

**Comment by mikhailswift** [comment]
> I don't know that I can create a PR against a tag, I think it has to be against a branch. So if this looks good and I submit I'm not sure which branch to use or if you would create one off of the v0.1.12 tag.

Creating one off of the v0.1.12 tag should be fine.

> 1) It seems the rekor integration only really works with the ed25519 key type.

If memory serves this is because rekor validates RSA signatures with the PKCSv1.5 scheme by default whereas witness uses the RSA-PSS scheme by default similarly to in-toto. I think I had worked around this in testifysec/rekor by manually creating a RSAPSS verifier instead. This isn't a real solution though so we may have to work with the rekor team to figure out a good solution for that problem.

>  2) the test cases seem to still have "dsse" type in the responses. I'm not sure I'm able to regenerate test cases without a key.

I can take a look and fix up the test cases for this.

**Comment by jmeth** [comment]
When I try to create a PR the 'Create' button goes away when selecting the `v0.1.12` tag. I think I need to specify a branch. The work I did was branched off of the v0.1.12 tag so if I just select `main` for the target I'm not sure if I would be introducing any issues with the go.mod for example since main has moved ahead of v0.1.12 by now.

![image](https://user-images.githubusercontent.com/2805627/195212754-a083ac50-491c-4ab5-8948-9559491c27d3.png)

**Comment by mikhailswift** [comment]
Ahhh, I see now. I created a branch `version/0.1.12` on go-witness, you should be able to open your PR against that

**Comment by colek42** [comment]
We want to implement rekor support as a hashed rekord.  This would allow users to keep their data private while using the public good instance to distribute trust and transparency,
