### ISSUE TITLE
Go version in go.mod needs to bump to 1.19

### ISSUE THREAD

**Issue by teq0** [testifysec/witness#225]
Since witness uses testifysec/archivist-api, and archivist-api uses url.JoinPath, which was introduced in go 1.19, the go version in go.mod needs to be bumped from 1.18 to 1.19.

Issue already raised for archivist-api - https://github.com/testifysec/archivist-api/issues/6

**Comment by mikhailswift** [comment]
Thanks for letting us know :) Fixed in #227
