### ISSUE TITLE
epic: Witness to Support Vault API as a Key Provider

### ISSUE THREAD

**Issue by colek42** [testifysec/witness#267]
## linked stories to this epic:
- https://github.com/testifysec/judge/issues/72
- https://github.com/testifysec/judge/issues/73

We need to support the Vault API as a key provider. For this iteration, we should assume the user has performed authentication with the Vault server and has the token stored in VAULT_TOKEN.

The Vault key provider will need the following options:

- Env variable or file the token is stored in (optional)
- Vault Server
- Role Name
- TTL (optional)

We are assuming that Vault has already been configured with Vault PKI enabled, a CA, Role with a short-lived TTL.

The Witness should generate a CSR by sending a sign request to '/pki/sign/<role name>' with the CSR and TTL. The CSR generation should follow the Vault API's guidelines for the '/pki/sign/:role' endpoint.

Here are the additional details to consider:

1. **CSR Generation**: The CSR should be sent in the request body as a PEM-encoded string. The CSR should not contain a requested Subject Alternative Name (SAN) as Vault will ignore these values and use the ones configured on the role.

2. **TTL**: If provided, the TTL (Time To Live) will be used to restrict the duration of the certificate. The TTL should be provided as a string duration with time suffix. Vault will encode the TTL into the certificate. If not provided, the role's TTL will be used.

3. **Non-Repudiation**: If the key is going to be used for creating digital signatures other than in a TLS handshake (e.g., for JWT tokens), then the 'key_usage' parameter should include 'DigitalSignature'.

4. **Error Handling**: If the role does not exist, or the backend does not exist, or if the CSR is malformed, Vault will return a 400 error. If the backend is not configured, or if the backend does not support the sign function, Vault will return a 500 error.

5. **Response Handling**: The response will be a JSON object with a data field containing two values: certificate and issuing_ca. The certificate field includes the PEM-encoded signed certificate. The issuing_ca field includes the PEM-encoded issuing CA certificate.

Reference: [Vault API Documentation - PKI](https://developer.hashicorp.com/vault/api-docs/secret/pki)

**Comment by colek42** [comment]
Vault Cluster:  https://portal.cloud.hashicorp.com/services/vault/sample-cluster?project_id=c1e41a09-8b23-4565-89f1-c70afd8ab2ec

**Comment by mikhailswift** [comment]
This made it's way into the v0.1.14 of witness 🎉
